name: Build Custom Kernel DEB
'on':
  workflow_dispatch: null
  workflow_call:
    inputs:
      _cpusched:
        required: true
        type: string

env:
  _modprobeddb_db_path: '${{ github.workspace }}/modprobed.db'

jobs:
  build_kernel:
    env:
      _cpusched: '${{ inputs._cpusched }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bc bison build-essential ccache cpio fakeroot flex git kmod libdw-dev libelf-dev libncurses-dev libssl-dev lz4 rsync schedtool wget zstd lld pkg-config devscripts make gcc ccache debhelper llvm clang
          version: 1.0

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Install deps and compile kernel
        run: yes '' | ./install.sh install

      - name: Cleanup useless DEB files
        run: rm -rf DEBS/*dbg*.deb DEBS/*libc-dev*.deb

      - name: rename kernel config
        run: 'mv kernelconfig.new kernelconfig.ubuntu.${{ env._cpusched }}.txt'

      - uses: actions/upload-artifact@v4
        with:
          name: 'ubuntu-kernel-packages-${{ env._cpusched }}'
          path: |
            DEBS/*.deb
            kernelconfig*.txt
